### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by 0108lijunshuai** [wangjianxiandev/WanAndroidMVVM#1]
大神，感觉你的base中东西太多了，能不能简化些

**Comment by wangjianxiandev** [comment]
好的~正在修改，这是我学习MVVM的项目，不足之处请多多指教！

**Comment by wangjianxiandev** [comment]
> 大神，感觉你的base中东西太多了，能不能简化些

好的~正在修改，这是我学习MVVM的项目，不足之处请多多指教！
