### ISSUE TITLE
网络请求状态

### ISSUE THREAD

**Issue by kebino1** [wangjianxiandev/WanAndroidMVVM#2]
大佬现在好像没有处理网络状态，例如没有网络，网络连接超时等

**Comment by wangjianxiandev** [comment]
> 大佬现在好像没有处理网络状态，例如没有网络，网络连接超时等

之前学习使用协程的时候忘记加了，刚刚加进去啦，谢谢~

**Comment by kebino1** [comment]
大佬再请教下，我看到你现在的请求遇到异常都是在一个单例类里面处理，只处理了连接异常，如果我出现gson解析错误（可能后台不规范，返回字段的类型不一致），应该怎么处理呢，你好像是返回一个新异常，但是没有返回具体的异常。

**Comment by wangjianxiandev** [comment]
> 大佬再请教下，我看到你现在的请求遇到异常都是在一个单例类里面处理，只处理了连接异常，如果我出现gson解析错误（可能后台不规范，返回字段的类型不一致），应该怎么处理呢，你好像是返回一个新异常，但是没有返回具体的异常。

is JsonParseException -> {
         loadState.postValue(State(StateType.ERROR))
}

**Comment by wangjianxiandev** [comment]
> 大佬再请教下，我看到你现在的请求遇到异常都是在一个单例类里面处理，只处理了连接异常，如果我出现gson解析错误（可能后台不规范，返回字段的类型不一致），应该怎么处理呢，你好像是返回一个新异常，但是没有返回具体的异常。

你好~ 
is JsonParseException -> {
        loadState.postValue(State(StateType.NETWORK_ERROR))
}

**Comment by fuckingcoding** [comment]
接口报错没有回显。
比如填错密码，收藏成功/取消等。
建议有空加一加。刚登录忘了密码。干怼半天按钮。。

**Comment by wangjianxiandev** [comment]
> 接口报错没有回显。
> 比如填错密码，收藏成功/取消等。
> 建议有空加一加。刚登录忘了密码。干怼半天按钮。。

收到~
