### ISSUE TITLE
 SpeedLayoutManager(context, 10f)

### ISSUE THREAD

**Issue by zenghuiwang** [wangjianxiandev/WanAndroidMVVM#3]
这个类是如何写的？

**Comment by wangjianxiandev** [comment]
> 这个类是如何写的？
创建LinearSmoothScroller对象  {
    重写LinearSmoothScroller的calculateSpeedPerPixel控制滑动速率
}
绑定目标位置  {
  smoothScroller.targetPosition = position
}
开始动画 {
 startSmoothScroll(smoothScroller)
}

**Comment by zenghuiwang** [comment]
是故意没放项目里吗

**Comment by wangjianxiandev** [comment]
> 是故意没放项目里吗

WanAndroidMVVM/app/src/main/java/com/wjx/android/wanandroidmvvm/common/utils/SpeedLayoutManager.kt
