### ISSUE TITLE
决定学习mvvm, 找了您的代码. 想请教个问题

### ISSUE THREAD

**Issue by mengbixiusi** [wangjianxiandev/WanAndroidMVVM#4]
/**
     * 分发应用状态
     */
    private val observer by lazy {
        Observer<State> {
            it?.let {
                EasyLog.json("===>"+it.code.toString())
                when (it.code) {
                    StateType.SUCCESS -> showSuccess()
                    StateType.LOADING -> showLoading()
                    StateType.ERROR -> showTip(it.message)
                    StateType.NETWORK_ERROR -> showError("网络出现问题啦")
                    StateType.TIP -> showTip(it.message)
                    StateType.EMPTY -> showEmpty()
                }
            }
        }
    }

 这里的 StateType.LOADING -> showLoading() 是不是不会执行,或者如何执行这一步的~

**Comment by wangjianxiandev** [comment]
> /**
> * 分发应用状态
> */
> private val observer by lazy {
> Observer {
> it?.let {
> EasyLog.json("===>"+it.code.toString())
> when (it.code) {
> StateType.SUCCESS -> showSuccess()
> StateType.LOADING -> showLoading()
> StateType.ERROR -> showTip(it.message)
> StateType.NETWORK_ERROR -> showError("网络出现问题啦")
> StateType.TIP -> showTip(it.message)
> StateType.EMPTY -> showEmpty()
> }
> }
> }
> }
> 
> 这里的 StateType.LOADING -> showLoading() 是不是不会执行,或者如何执行这一步的~

您好，这里这个Loading动画是 因为每个页面都会有加载动画，所以我选择的是在base中的initView()直接调用的showLoading()，并没有通过loadState进行状态的转发，如果在某个页面加载的过程中需要根据当前页面加载的需要显示loading的话，可以调用
loadState.postValue(State(StateType.LOADING)，可以参考com.wjx.android.wanandroidmvvm.base.observer.BaseObserver或者
com.wjx.android.wanandroidmvvm.network.Ext

**Comment by mengbixiusi** [comment]
ok,多谢回复

**Comment by wangjianxiandev** [comment]
> ok,多谢回复

MVVM的关键在于DataBinding，因为存在界面的复用问题，所以在项目中并没有使用，之后会在其他项目中体现，希望对您有帮助 👍

**Comment by meiniepan** [comment]
哥，能不能把混淆加上，我这加了跑不起来了
