### ISSUE TITLE
关于loadstate，发现了一个小问题

### ISSUE THREAD

**Issue by hurist** [wangjianxiandev/WanAndroidMVVM#5]
大佬你好，我在看代码的时候发现每个viewmodel都有一个loadState，所有viewmodel内的请求都是用的它来更新网络请求状态。
假设进入某个页面要同时发起两个请求，第一个成功，而第二个失败了，那么此时APP就会显示加载错误页面，这种状态应该是正常的。但如果是第一个失败，第二个成功了，那么此时APP则会显示加载成功的，而不会显示加载失败的状态页。

**Comment by wangjianxiandev** [comment]
> 大佬你好，我在看代码的时候发现每个viewmodel都有一个loadState，所有viewmodel内的请求都是用的它来更新网络请求状态。
> 假设进入某个页面要同时发起两个请求，第一个成功，而第二个失败了，那么此时APP就会显示加载错误页面，这种状态应该是正常的。但如果是第一个失败，第二个成功了，那么此时APP则会显示加载成功的，而不会显示加载失败的状态页。

十分感谢您提出的问题，确实存在第一个失败第二个成功仍正常加载的情况，现在正在尝试进行解决，有解决方案会第一时间回复您~

**Comment by wangjianxiandev** [comment]
> 大佬你好，我在看代码的时候发现每个viewmodel都有一个loadState，所有viewmodel内的请求都是用的它来更新网络请求状态。
> 假设进入某个页面要同时发起两个请求，第一个成功，而第二个失败了，那么此时APP就会显示加载错误页面，这种状态应该是正常的。但如果是第一个失败，第二个成功了，那么此时APP则会显示加载成功的，而不会显示加载失败的状态页。

您好，我这边想了一些方法，主要是因为一个ViewModel所持有的都是同一个loadState，如果页面存在多个模块分步加载的话是肯定会出现您描述的错误的，我在尝试是否可以将加载不成功的布局直接隐藏掉来进行解决，但是会因为错误模块loadState的失败状态导致闪现error page, 请问这个部分您是否有思路解决，希望收到您的答复，一起学习~

**Comment by hurist** [comment]
> > 大佬你好，我在看代码的时候发现每个viewmodel都有一个loadState，所有viewmodel内的请求都是用的它来更新网络请求状态。
> > 假设进入某个页面要同时发起两个请求，第一个成功，而第二个失败了，那么此时APP就会显示加载错误页面，这种状态应该是正常的。但如果是第一个失败，第二个成功了，那么此时APP则会显示加载成功的，而不会显示加载失败的状态页。
> 
> 您好，我这边想了一些方法，主要是因为一个ViewModel所持有的都是同一个loadState，如果页面存在多个模块分步加载的话是肯定会出现您描述的错误的，我在尝试是否可以将加载不成功的布局直接隐藏掉来进行解决，但是会因为错误模块loadState的失败状态导致闪现error page, 请问这个部分您是否有思路解决，希望收到您的答复，一起学习~

也是一个解决办法吧，我最近也在想遇到这种要怎么处理，好像用单个始终都会有这种问题，不知道还有什么其他好的错误处理方法
